[package]
name = "rrf"
version = "0.1.0"
edition = "2021"

[lib]
name = "ranx_module"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = {version = "0.20.3", features = ["extension-module"]}
